### PR TITLE
Changed to latest version

### PR DESCRIPTION
**Pull request by albertocoletta**

### CODE REVIEW

**Comment by calippo** [comment]
@boh717 I think best thing to do is just to leave "..." as we're doing in enumero (https://github.com/buildo/enumero).
The proper version will be inferred from maven.

**Comment by albertocoletta** [comment]
@calippo Does this trick works for documentation? Because the version on the guide is still old :)

**Comment by calippo** [comment]
@boh717 what I mean is:
`"io.buildo" %% "wiro-http-server" % "..."`

**Comment by gabro** [comment]
superseded by #62

**Pull request closed without merging**
