### PR TITLE
Updated build.sbt

### PR DESCRIPTION
**Pull request by federico-pellegatta**
Removed `tutSettings` from `build.sbt`, guess it is a typo.

### CODE REVIEW

**Comment by calippo** [comment]
@federico-pellegatta nope https://github.com/tpolecat/tut :P

**Comment by calippo** [comment]
Though I'm not already using it

**Comment by federico-pellegatta** [comment]
In that case you should add (commit) the proper `project/plugins.sbt` otherwise it does not compile properly.

**Comment by calippo** [comment]
@federico-pellegatta whops, didn't push it. Thanks!

**Pull request merged**
